# Generated by Django 4.0.4 on 2022-08-26 02:37

import base.helpers
import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default=base.helpers.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=1055)),
                ('avatar', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('problem_ids', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('token', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('token_expiresin', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact',
                'ordering': ['-created_at'],
            },
            bases=(base.models.BaseModel, models.Model),
        ),
    ]
