# Generated by Django 4.0.4 on 2022-08-26 03:52

import base.helpers
import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=base.helpers.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('sort_order', models.SmallIntegerField(default=255)),
                ('content', models.TextField(null=True)),
                ('content_short', models.CharField(max_length=1000, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('is_dev', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_created_by', to=settings.AUTH_USER_MODEL)),
                ('dynamic_id', models.ForeignKey(db_column='dynamic_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dynamic')),
                ('parent_id', models.ForeignKey(db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.document')),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document',
                'ordering': ['dynamic_id', 'name'],
            },
            bases=(base.models.BaseModel, models.Model),
        ),
    ]
