# Generated by Django 4.0.4 on 2022-07-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_category_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='created_id',
        ),
    ]
