# Generated by Django 4.0.4 on 2022-08-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
