# Generated by Django 4.0.4 on 2022-08-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
