# Generated by Django 4.0.4 on 2022-08-10 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_customuser_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
