# Generated by Django 4.0.4 on 2022-08-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_extend_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extend',
        ),
    ]
