# Generated by Django 4.0.4 on 2022-08-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_rename_extend_extend_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
